defaults:
  - model: lcnn
  - metrics: lcnn_asvspoof2019
  - dataloader: lcnn_asvspoof2019
  - transforms: lcnn_asvspoof2019
  - _self_

datasets:
  eval:
    _target_: src.datasets.ASVspoof2019LADataset
    audio_dir: "C:/Datasets/ASVspoof2019/LA/LA/ASVspoof2019_LA_eval/flac"
    protocol_path: "C:/Datasets/ASVspoof2019/LA/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt"
    shuffle_index: false
    instance_transforms: ${transforms.instance_transforms.inference}

inferencer:
  device_tensors: ["data_object", "labels"]
  device: auto
  non_blocking: True
  save_path: null
  submission_path: "C:/Users/russi/Downloads/students_solutions/mnbasin.csv"
  seed: 1
  from_pretrained: "saved/testing/model_best.pth"
